spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/porter_replica
    username: web_app_user
    password: web_app_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081